main/routes.py
from flask import render_template, request, Blueprint
# from flaskblog.models import Post

main = Blueprint('main', __name__)


@main.route("/")
# def mainpage():
# 	return render_template('mainpage.html')

# @main.route("/home")
# def home():
#     page = request.args.get('page', 1, type=int)
#     return render_template('home.html', title='Home')


@main.route("/info")
def info():
    return render_template('info.html', title='Info')



# @main.route("/mainpage")
# def mainpage():
#     return render_template('mainpage.html', title='Covid-19 Tracker')

users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint, Markup
from flask_login import login_user, current_user, logout_user, login_required, UserMixin
from flaskblog import db, bcrypt
from flaskblog.models import User
from flaskblog.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,UpdateHomeForm,
                                   RequestResetForm, ResetPasswordForm, UpdateMHomeForm,UpdateGraphForm)
from flaskblog.users.utils import save_picture, send_reset_email
from sqlalchemy.sql.functions import func


users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('users.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(
            username=form.username.data, 
            email=form.email.data, 
            password=hashed_password,
            department=form.department.data,
            manager=form.manager.data,
            job_title=form.job_title.data,
            supervisor=form.supervisor.data,
            high_risk=form.high_risk.data,
            health=form.health.data,
            h_comment=form.h_comment.data,
            employment=form.employment.data,
            e_comment=form.e_comment.data,
            date_updated=form.date_updated.data)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated: 
            return redirect(url_for('users.mainpage'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('users.mainpage'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('users.login'))
    # return redirect(url_for('main.home'))

@users.route("/mainpage")
def mainpage():
    return render_template('mainpage.html', title='Main')


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.job_title = form.job_title.data
        current_user.department = form.department.data
        current_user.supervisor = form.supervisor.data
        current_user.manager = form.manager.data
        current_user.high_risk = form.high_risk.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.job_title.data = current_user.job_title
        form.department.data = current_user.department
        form.supervisor.data = current_user.supervisor
        form.manager.data = current_user.manager
        form.high_risk.data = current_user.high_risk
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)

@users.route("/home", methods=['GET', 'POST'])
@login_required
def home():
    if current_user.manager.lower() == 'yes':
        return redirect(url_for('users.option'))
    # elif current_user.manager.lower() == 'no':
    #     return redirect(url_for('users.home'))

    form = UpdateHomeForm()
    if form.validate_on_submit():
        current_user.health = form.health.data
        current_user.h_comment = form.h_comment.data
        current_user.employment = form.employment.data
        current_user.e_comment = form.e_comment.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.home'))
        # return redirect(url_for('main.home'))
    elif request.method == 'GET':
        form.health.data = current_user.health
        form.h_comment.data = current_user.h_comment
        form.employment.data = current_user.employment
        form.e_comment.data = current_user.e_comment
    return render_template('home.html', title='Home', form=form)

@users.route("/m_home", methods=['GET', 'POST'])
@login_required
def option():
    form = UpdateMHomeForm()
    if form.validate_on_submit():
        option = form.option.data
        if option == 'Analytics':
            return redirect(url_for('users.analytics'))
        elif option == 'Graphs':
            return redirect(url_for('users.graphs'))
        elif option == 'Search':
            return redirect(url_for('users.search'))     
    return render_template('m_home.html', title='MHome', form=form)
        

@users.route("/m_home/analytics")
def analytics():
    case_total = User.query.filter_by(health='covid').count()
    employees_total = case_total + User.query.filter_by(health='covid-free').count()
    case_percent = ("%.0f%%" % (100 * case_total / employees_total))
    home_total = User.query.filter_by(employment='working from home').count()
    office_total = User.query.filter_by(employment='working in office').count()
    part_time_total = User.query.filter_by(employment='part-time in office').count()
    
    return render_template('analytics.html', title='Analytics', case_total=case_total, home_total=home_total, office_total=office_total, part_time_total=part_time_total, employees_total=employees_total, case_percent=case_percent)


@users.route("/m_home/graphs", methods=['GET', 'POST'])
def graphs():
    form = UpdateGraphForm()
    if form.validate_on_submit():
        option = form.option.data
        if option == 'Line graph':
            return redirect(url_for('users.line'))
        elif option == 'Bar chart':
            return redirect(url_for('users.bar'))
        elif option == 'Pie chart':
            return redirect(url_for('users.pie'))     
    return render_template('graphs.html', title='Graphs',form=form)

@users.route("/m_home/graphs/bar")
def bar():
    home_total = User.query.filter_by(employment='working from home').count()
    office_total = User.query.filter_by(employment='working in office').count()
    part_time_total = User.query.filter_by(employment='part-time in office').count()

    labels = ['Working from Home', 'Working in office', 'Part-time in office']
    values = [home_total,office_total,part_time_total]
    return render_template('bar.html', title='Bar Chart',max=5, labels=labels, values=values)

@users.route("/m_home/graphs/pie")
def pie():
    case_total = User.query.filter_by(health='covid').count()
    employees_total = User.query.filter_by(manager= 'yes').count() + User.query.filter_by(manager= 'no').count()
    covid_free_total = employees_total - case_total

    labels = ['Covid', 'Covid-free']
    values = [case_total,covid_free_total]
    colors = ["#F7464A","#46BFBD"]
    return render_template('pie.html', title='Pie Chart',max=5, set=zip(values,labels,colors))

@users.route("/m_home/graphs/line")
def line():

    # # https://flaskage.readthedocs.io/en/latest/database_queries.html

    total = 0
    september = total + (User.query.filter_by(health='covid').filter_by(date_updated = '2020-09-27 19:35:45.840362')).count()
    october = september + (User.query.filter_by(health='covid').filter_by(date_updated = '2020-10-27 19:35:45.840362')).count()
    november = october + (User.query.filter_by(health='covid').filter_by(date_updated = '2020-11-27 19:35:45.840362')).count()
    december = november + (User.query.filter_by(health='covid').filter_by(date_updated = '2020-12-27 19:35:45.840362')).count()
    january = december + (User.query.filter_by(health='covid').filter_by(date_updated = '2021-01-27 19:35:45.840362')).count()
    february = january + (User.query.filter_by(health='covid').filter_by(date_updated = '2021-02-27 19:35:45.840362')).count()
    march = february + (User.query.filter_by(health='covid').filter_by(date_updated = '2021-03-27 19:35:45.840362')).count()
    
    labels = ['Sept', 'Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar']
    values = [september, october,november,december,january, february, march]
    # labels = ['Sat', 'Sun', 'Mon', 'Tue', 'Wed','Thu','Fri']
    # values = [saturday, sunday,monday,tuesday,wednesday,thursday,friday]
        
    return render_template('line.html', title='Monthly covid rates',max=25, labels=labels, values=values)



@users.route("/m_home/search")
def search():
    return render_template('search.html', title='Search')






@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

templates/account.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
	  <div class="media">
		<img class="rounded-circle account-img" src="{{ image_file }}">
		<div class="media-body">
		  <h2 class="account-heading">{{ current_user.username }}</h2>
		  <p class="text-secondary">{{ current_user.email }}</p>
		</div>
	  </div>
		<form method="POST" action="" enctype="multipart/form-data">
				{{ form.hidden_tag() }}
				<fieldset class="form-group">
					<legend class="border-bottom mb-4">Account Info</legend>
					<div class="form-group">
						{{ form.username.label(class="form-control-label") }}

						{% if form.username.errors %}
							{{ form.username(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback" >
								{% for error in form.username.errors %}
									<span>{{ error }} </span>
								{% endfor %}
							</div>
							{% else %}
								 {{ form.username(class="form-control form-control-lg") }}
							{% endif %}
					</div>
					<div class="form-group">
						{{ form.email.label(class="form-control-label") }}
						{% if form.email.errors %}
							{{ form.email(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.email.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.email(class="form-control form-control-lg") }}
						{% endif %}
					</div>

					<div class="form-group">
						{{ form.picture.label() }}
						{{ form.picture(class="form-control-file") }}
						{% if form.picture.errors %}
							{% for error in form.picture.errors %}
								<span class="text-danger">{{ error }}</span></br>
							{% endfor %}
						{% endif %}
					</div>

					<div class="form-group">
						{{ form.job_title.label(class="form-control-label") }}
						{% if form.job_title.errors %}
							{{ form.job_title(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.job_title.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.job_title(class="form-control form-control-lg") }}
						{% endif %}
					</div>

					<div class="form-group">
						{{ form.department.label(class="form-control-label") }}
						{% if form.department.errors %}
							{{ form.department(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.department.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.department(class="form-control form-control-lg") }}
						{% endif %}
					</div>

					<div class="form-group">
						{{ form.supervisor.label(class="form-control-label") }}
						{% if form.supervisor.errors %}
							{{ form.supervisor(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.supervisor.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.supervisor(class="form-control form-control-lg") }}
						{% endif %}
					</div>

					<div class="form-group">
						{{ form.manager.label(class="form-control-label") }}
						{% if form.manager.errors %}
							{{ form.manager(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.manager.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.manager(class="form-control form-control-lg") }}
						{% endif %}
					</div>

					<div class="form-group">
						{{ form.high_risk.label(class="form-control-label") }}
						{% if form.high_risk.errors %}
							{{ form.high_risk(class="form-control form-control-lg is-invalid") }}
							<div class="invalid-feedback">
								{% for error in form.high_risk.errors %}
									<span>{{ error }}</span>
								{% endfor %}
							</div>
						{% else %}
							{{ form.high_risk(class="form-control form-control-lg") }}
						{% endif %}
					</div>

				</fieldset>

				<div class="form-group">
					{{ form.submit(class="btn btn-outline-info") }}
				</div>
		</form>

	</div>
{% endblock content %}

templates/analytics.html
{% extends "layout.html" %}
{% block content %}

	<h2>Analytics page</h2>
	<hr>
	<br>
	<div>
		<p>Total Number of Employees: {{employees_total}}</p>
		<p>Total % of employees with covid : {{case_percent}} </p>
		<p>Total Number of Covid Cases: {{case_total}}</p>
		<p>Employees working from home: {{home_total}}</p>
		<p>Part-time in the office: {{office_total}}</p>
		<p>Employees working from office:{{part_time_total}}</p>
	</div>		



{% endblock content %}

templates/bar.html
{% extends "layout.html" %}
{% block content %}
	<h2>Bar graph</h2>
		
<title>{{ title }}</title>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>
</head>

<body>

  <center>
    <canvas id="chart" width="600" height="400"></canvas>
    <script>
      // bar chart data
      var barData = {
        labels : [
          {% for item in labels %}
           "{{ item }}",
          {% endfor %}
	],

        datasets : [{
          fillColor: "rgba(151,187,205,0.2)",
          strokeColor: "rgba(151,187,205,1)",
          pointColor: "rgba(151,187,205,1)",
          data : [
            {% for item in values %}
               "{{ item }}",
              {% endfor %}
	    ]
          }
        ]
      }

     // get bar chart canvas
     var mychart = document.getElementById("chart").getContext("2d");

       steps = 10
       max = {{max}}

     // draw bar chart
     new Chart(mychart).Bar(barData, {
       scaleOverride: true,
       scaleSteps: steps,
       scaleStepWidth: Math.ceil(max / steps),
       scaleStartValue: 0,
       scaleShowVerticalLines: true,
       scaleShowGridLines : true,
       barShowStroke : true,
       scaleShowLabels: true
       }
     );

    </script>
  </center>
</body>







{% endblock content %}

templates/home.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <div class="media">
    <div class="media-body">
      <h2 class="account-heading">{{ current_user.username }}</h2>
      <!-- <p class="text-secondary">{{ current_user.email }}</p> -->
    </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <div class="form-group">
            {{ form.health.label(class="form-control-label") }}

            {% if form.health.errors %}
              {{ form.health(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback" >
                {% for error in form.health.errors %}
                  <span>{{ error }} </span>
                {% endfor %}
              </div>
              {% else %}
                 {{ form.health(class="form-control form-control-lg") }}
              {% endif %}
          </div>
          
          <div class="form-group">
            {{ form.h_comment.label(class="form-control-label") }}
            {% if form.h_comment.errors %}
              {{ form.h_comment(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.h_comment.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.h_comment(class="form-control form-control-lg") }}
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.employment.label(class="form-control-label") }}
            {% if form.employment.errors %}
              {{ form.employment(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.employment.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.employment(class="form-control form-control-lg") }}
            {% endif %}
          </div>

          <div class="form-group">
            {{ form.e_comment.label(class="form-control-label") }}
            {% if form.e_comment.errors %}
              {{ form.e_comment(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback">
                {% for error in form.e_comment.errors %}
                  <span>{{ error }}</span>
                {% endfor %}
              </div>
            {% else %}
              {{ form.e_comment(class="form-control form-control-lg") }}
            {% endif %}
          </div>

        </fieldset>

        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

  </div>
{% endblock content %}

templates/info.html
{% extends "layout.html" %}
{% block content %}


	<h2>Info Page</h2>
		<p>Current government coronavirus (COVID-19) advice is that anyone who can work effectively from home should do so. </p>
		<p>For workplaces that are open, everyone should:
			<ul>
				 <li>follow government guidance on making the workplace safe</li>
 				 <li>avoid busy commuting times on public transport where travel is essential, and wear a face covering unless they're exempt</li>
 				 <li>wash their hands regularly</li>
			</ul>
		</p>

		<p>IMPORTANT: You must not go to work if you or anyone in your household has symptoms.</p>
	
	<p><h3>Important Links:</h3></p>
		<p><a href="https://www.gov.uk/coronavirus">Governmental Updates</a></p>
		<p><a href="https://www.citizensadvice.org.uk/work/coronavirus-if-youre-worried-about-working/?priority-taxon=5ebf285a-9165-476c-be90-66b9729f50da">Workplace guidelines</a></p>
		<p><a href="https://www.gov.uk/guidance/coronavirus-covid-19-what-to-do-if-youre-employed-and-cannot-work?priority-taxon=5ebf285a-9165-476c-be90-66b9729f50da">Financial Support</a></p>
		<p><a href="https://www.gov.uk/government/publications/coronavirus-covid-19-meeting-with-others-safely-social-distancing/coronavirus-covid-19-meeting-with-others-safely-social-distancing?priority-taxon=774cee22-d896-44c1-a611-e3109cce8eae">Getting to work safely</a></p>
		<p><a href="https://www.gov.uk/tax-relief-for-employees/working-at-home?priority-taxon=5ebf285a-9165-476c-be90-66b9729f50da">Working from home</a></p>


{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}"

	</head>
<body>
	<header class="site-header">
	  <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
		<div class="container">
<!-- 		  <a class="navbar-brand mr-4" href="/">Covid-19 Tracker</a>
 -->		  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		  </button>
		  <div class="collapse navbar-collapse" id="navbarToggle">
			<div class="navbar-nav mr-auto">
				{% if current_user.is_authenticated %}
						{% if current_user.manager == 'yes' %}
			  				<a class="nav-item nav-link" href="{{ url_for('users.option') }}">Home</a>
 							<a class="nav-item nav-link" href="{{ url_for('main.info') }}">Info</a>
			  				<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
			  			{% else %}
 							<a class="nav-item nav-link" href="{{ url_for('users.home') }}">Home</a>
 							<a class="nav-item nav-link" href="{{ url_for('main.info') }}">Info</a>
			  				<a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
			  			{% endif %}
				{% else %}
					<a class="nav-item nav-link" href="{{ url_for('users.mainpage') }}">Main</a>
				{% endif %}
			</div>
			<!-- Navbar Right Side -->
			<div class="navbar-nav">
				{% if current_user.is_authenticated %}
					<a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
				{% else %}
					<a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
					<a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
			  {% endif %}
			</div>
		  </div>
		</div>
	  </nav>
</header>
	<main role="main" class="container">
	  <div class="row">
		<div class="col-md-8">
		{% with messages = get_flashed_messages(with_categories=true) %}
			{% if messages%}
				{% for category, message in messages %}
					<div class="alert alert-{{ category }}">
						{{ message }}
					</div>	
				{% endfor %}
			{% endif %}
		{% endwith %}

		  {% block content %}{% endblock content %}

		
		</div>
		
	  </div>
	</main>
		

	 <!-- Optional JavaScript -->
	<!-- jQuery first, then Popper.js, then Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
 
</body>
</html>

templates/line.html
{% extends "layout.html" %}
{% block content %}


  <h2>Monthly covid rates</h2>

  <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>

<body>
  <center>
    <canvas id="chart" width="600" height="400"></canvas>
    <script>

      // bar chart data
      var barData = {
        labels : [
          {% for item in labels %}
            "{{ item }}",
          {% endfor %}
        ],

        datasets : [{
          fillColor: "rgba(151,187,205,0.2)",
          strokeColor: "rgba(151,187,205,1)",
          pointColor: "rgba(151,187,205,1)",
          pointStrokeColor: "#fff",
          pointHighlightFill: "#fff",
          pointHighlightStroke: "rgba(151,187,205,1)",
          bezierCurve : false,
          data : [
	    {% for item in values %}
              {{ item }},
            {% endfor %}]
          }
	]
      }

      Chart.defaults.global.animationSteps = 50;
      Chart.defaults.global.tooltipYPadding = 16;
      Chart.defaults.global.tooltipCornerRadius = 0;
      Chart.defaults.global.tooltipTitleFontStyle = "normal";
      Chart.defaults.global.tooltipFillColor = "rgba(0,0,0,0.8)";
      Chart.defaults.global.animationEasing = "easeOutBounce";
      Chart.defaults.global.responsive = false;
      Chart.defaults.global.scaleLineColor = "black";
      Chart.defaults.global.scaleFontSize = 16;

      // get bar chart canvas
      var mychart = document.getElementById("chart").getContext("2d");

      steps = 10
      max = {{ max }}
      // draw bar chart
      var LineChartDemo = new Chart(mychart).Line(barData, {
        scaleOverride: true,
        scaleSteps: steps,
        scaleStepWidth: Math.ceil(max / steps),
        scaleStartValue: 0,
        scaleShowVerticalLines: true,
        scaleShowGridLines : true,
        barShowStroke : true,
        scaleShowLabels: true,
        bezierCurve: false,
      });

    </script>
  </center>
</body>

{% endblock content %}

templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                     <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
            </div>
            
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

templates/m_home.html
{% extends "layout.html" %}
{% block content %}
  <div class="content-section">
    <div class="media">
      <img src="{{url_for('static', filename='statistics.png')}}" align="left" />
      <img src="{{url_for('static', filename='graphs.png')}}" align="middle" />
      <img src="{{url_for('static', filename='search.png')}}" align="right" />
    <div class="media-body">
    </div>
    </div>
    <form method="POST" action="" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
          <div class="form-group">
            {{ form.option.label(class="form-control-label") }}

            {% if form.option.errors %}
              {{ form.option(class="form-control form-control-lg is-invalid") }}
              <div class="invalid-feedback" >
                {% for error in form.option.errors %}
                  <span>{{ error }} </span>
                {% endfor %}
              </div>
              {% else %}
                 {{ form.option(class="form-control form-control-lg") }}
              {% endif %}
          </div>
        </fieldset>

        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>

  </div>
{% endblock content %}

templates/mainpage.html
{% extends "layout.html" %}
{% block content %}


  <h2>Welcome {{ current_user.username }} !</h2>
   


{% endblock content %}